name: Movie parley production CI/CD pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: baddockerhub/movieparley-frontend:${{github.run_number}}
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to Digital Ocean
        run: |
          # authorize kubectl to execute on the cluster
          doctl kubernetes cluster kubeconfig save movie-parley-cluster
          sed -i -e "s/app-version-placeholder/${{ github.run_number }}/g" deployment/digital_ocean/deployment.yml
          # the cluster should already be authorized to download from dockerhub. Otherwise take care of that first from
          # the command line
          kubectl apply -f deployment/digital_ocean/deployment.yml
